apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "parkshare.fullname" . }}-config
  labels:
    {{- include "parkshare.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
