apiVersion: v1
kind: Secret
metadata:
  name: {{ include "parkshare.fullname" . }}-secrets
  labels:
    {{- include "parkshare.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.secrets.database.url | quote }}
  redis-password: {{ .Values.secrets.redis.password | quote }}
  jwt-secret: {{ .Values.secrets.jwt.secret | quote }}
  jwt-refresh-secret: {{ .Values.secrets.jwt.refreshSecret | quote }}
