apiVersion: v1
kind: Service
metadata:
  name: parkshare-api
  namespace: parkshare
  labels:
    app: parkshare-api
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: parkshare-api
---
apiVersion: v1
kind: Service
metadata:
  name: parkshare-api-headless
  namespace: parkshare
  labels:
    app: parkshare-api
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: parkshare-api
